# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  release:
    types: [created]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
          
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
#     - name: sed
#       run:  sed -i 's+my-app-1.0-SNAPSHOT.jar+my-app-1.0.1-SNAPSHOT.jar+g' Dockerfile

    - name: update file and push to remote
      run: |
          cd my-app
          git config --global user.name "sarrihoffman"
          git config --global user.email "sh0533135692@gmail.com"
          
          
    - name: Build with Maven 
      run: |
            pwd
            ls my-app
            mvn -B package --file my-app/pom.xml
            tree
    - name: Build Docker Image
      run: docker image build -t sarahofman/maven-hello-world .
    -
   
      name: Push to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
#         push: true 
#         tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-hello-world 

    - name: push-pom
      run: |
          git add -A
          git commit -m "Update pom.xml"
          git push
          
    - name: Push
      run: docker push sarahofman/maven-hello-world
    - name: Pull
      run: docker pull sarahofman/maven-hello-world:latest

    - name: Run
      run: docker run sarahofman/maven-hello-world:latest
